; INSTRUCTION_CONSTANTS.ASM
;-------------------------------

; Typing constants
INSTRUCTION_TYPE__MOVE_RIGHT equ 1
INSTRUCTION_TYPE__MOVE_LEFT equ 2
INSTRUCTION_TYPE__INCREMENT equ 3
INSTRUCTION_TYPE__DECREMENT equ 4
INSTRUCTION_TYPE__OUTPUT equ 5
INSTRUCTION_TYPE__INPUT equ 6
INSTRUCTION_TYPE__LOOP_L equ 7
INSTRUCTION_TYPE__LOOP_R equ 8

; Jumping addresses constants
INSTRUCTION__NO_JUMP equ 0

; Character constants
INSTRUCTION_CHAR__MOVE_RIGHT equ '>'
INSTRUCTION_CHAR__MOVE_LEFT equ '<'
INSTRUCTION_CHAR__INCREMENT equ '+'
INSTRUCTION_CHAR__DECREMENT equ '-'
INSTRUCTION_CHAR__OUTPUT equ '.'
INSTRUCTION_CHAR__INPUT equ ','
INSTRUCTION_CHAR__LOOP_L equ '['
INSTRUCTION_CHAR__LOOP_R equ ']'
